#!/usr/bin/env bash
# Writes the Homebrew formula for one release to stdout.
#
#   scripts/homebrew-formula.sh 0.2.1 path/to/SHA256SUMS >Formula/varis.rb
#
# Run by .github/workflows/release.yml, which commits the result to the
# AugustineOjeh/homebrew-tap repository, so developers can run:
#
#   brew install augustineojeh/tap/varis
#
# The formula installs the prebuilt binary for the machine: one archive per
# platform, each pinned by its SHA-256 from the release's SHA256SUMS, so
# Homebrew refuses a download that doesn't match. Nothing is compiled.
#
# Formulae, unlike casks, don't get macOS's quarantine flag, so Gatekeeper
# doesn't stop the ad-hoc-signed binary.

set -euo pipefail

if [ $# -ne 2 ]; then
  echo "Usage: $0 <version> <SHA256SUMS file>" >&2
  exit 2
fi

version="$1"
sums="$2"
base="https://github.com/AugustineOjeh/varis-cli/releases/download/v$version"

# The checksum for one archive, or a failure if SHA256SUMS lacks it: a
# formula with a missing checksum must never be written.
sum() {
  local line
  line="$(grep " $1\$" "$sums")" || {
    echo "SHA256SUMS has no entry for $1" >&2
    exit 1
  }
  echo "${line%% *}"
}

# Read into variables before writing anything. A failure inside the
# heredoc below would only end a subshell, and cat would still succeed.
darwin_arm64="$(sum varis-darwin-arm64.tar.gz)"
darwin_x64="$(sum varis-darwin-x64.tar.gz)"
linux_arm64="$(sum varis-linux-arm64.tar.gz)"
linux_x64="$(sum varis-linux-x64.tar.gz)"

cat <<EOF
# Generated by the varis-cli release workflow (scripts/homebrew-formula.sh
# in AugustineOjeh/varis-cli). Don't edit it here: each release replaces it.
class Varis < Formula
  desc "Publish services that AI agents discover and pay to use"
  homepage "https://github.com/AugustineOjeh/varis-cli"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/varis-darwin-arm64.tar.gz"
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "$base/varis-darwin-x64.tar.gz"
      sha256 "$darwin_x64"
    end
  end

  on_linux do
    on_arm do
      url "$base/varis-linux-arm64.tar.gz"
      sha256 "$linux_arm64"
    end
    on_intel do
      url "$base/varis-linux-x64.tar.gz"
      sha256 "$linux_x64"
    end
  end

  def install
    bin.install "varis"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/varis --version").strip
  end
end
EOF
